language: python
python:
  - "2.6"
  - "2.7"
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.6"
  - "3.7"
  - "3.8"
  - "pypy"
  - "pypy3"
dist: trusty
#jobs:
#  include:
#    - python: 3.7
#      dist: xenial
# command to install dependencies
install: "pip install -r requirements.txt"
# command to run tests
script:
- cd hulusubs_dl
- python __main__.py --version
notifications:
  email:
    - xonshiz@gmail.com
deploy:
  provider: pypi
  username: xonshiz
  password:
    secure: lHfaeruvQM4QL3hk1+wSwVSNjkeQH153X9Oi+nY1SaahjEg1l9mNaubfq7l8mNRgbZzW3yOHswDOLz6bNlSKX9xnjecl/5jVOg97ImChujtwZobGmCJuSBq+F2HGt3KnJefjgv2E/kAMgKPLJJSZHIGzxaYDLyRiz8hr6aMdPFEU8rY8Ha4OpHOCjQrZOULgUYQs/UR2FzjI6QhIqHOlc+reZbtADI9Z69i16iTXf+isAFgwEW+Na/uxODT3kXgt5HXxNayODPlMCVBABfWyDajoeJFmYE90hggPI3FmBn9rapTEIJMMDhT5Sh/T7lIVgyJGBA6eT4lBiEPgB4CS8Vbh6nW00RjrgYWMDPMpxqNA3hBCRsQ1zpOQc5idH8yxS2Y+7GxwWqcqmGiuvE0/a0ytU5vDeM+VkjSN1irFEW1tAPjMNHLK8aPDDteu0qCyhDK17W4NOuZ8DQgxjvPwsSIElQOTnEy4UdXNkcQa8rnPIHnHa0ceoOZI1gYdn/xlrKcmXmGSGCi4KBpo1bQ1fC6QnHleKsognpNAr4diJxgqDjRMUmcfQOWW8c2hji2xUH34amvVMZVpbJu1zkM/o8I7upaAjwE6H/s7Azo2X/sKYyH0uJDeWYrTHofp9M3yWJKJQ3/nqzG8Ete9caZBbKcj0pb6RXdJ8iAR4JLUDJE=
  distributions: "sdist bdist_wheel"