matrix:
  include:
    - language: python
      python:
        - 2.6
      dist: trusty
      before_install:
        - "wget https://files.pythonhosted.org/packages/b5/a8/56be92dcd4a5bf1998705a9b4028249fe7c9a035b955fe93b6a3e5b829f8/asn1crypto-1.4.0-py2.py3-none-any.whl"
        - "wget https://files.pythonhosted.org/packages/6f/2c/a9386903ece2ea85e9807e0e062174dc26fdce8b05f216d00491be29fad5/enum34-1.1.10-py2-none-any.whl"
        - "wget https://files.pythonhosted.org/packages/d7/77/ff688d1504cdc4db2a938e2b7b9adee5dd52e34efbd2431051efc9984de9/idna-3.2-py3-none-any.whl"
        - "wget https://files.pythonhosted.org/packages/d9/5a/e7c31adbe875f2abbb91bd84cf2dc52d792b5a01506781dbcf25c91daf11/six-1.16.0-py2.py3-none-any.whl"
        - "wget https://files.pythonhosted.org/packages/c2/f8/49697181b1651d8347d24c095ce46c7346c37335ddc7d255833e7cde674d/ipaddress-1.0.23-py2.py3-none-any.whl"
        - "wget https://files.pythonhosted.org/packages/b2/5e/06351ede29fd4899782ad335c2e02f1f862a887c20a3541f17c3fa1a3525/pyOpenSSL-20.0.1-py2.py3-none-any.whl"
        - "wget https://files.pythonhosted.org/packages/1f/f5/b66668d5b18b03cf75fcb3fa1108a04b22b2e108fed5e99efe9e3214f325/cffi-1.14.5-cp27-cp27m-manylinux1_x86_64.whl"
        - "wget https://files.pythonhosted.org/packages/12/54/706ec35369a8f9dd23e5f62bfe26ef84543e08bbdb6ff5b0772ec1028282/cryptography-3.3.1-cp27-cp27m-manylinux1_x86_64.whl"
        - "wget https://files.pythonhosted.org/packages/0f/86/e19659527668d70be91d0369aeaa055b4eb396b0f387a4f92293a20035bd/pycparser-2.20.tar.gz"
        - "mkdir hulusubs_dl/wheels_dir"
        - "ls hulusubs_dl/wheels_dir"
        - pip install --no-index "hulusubs_dl/wheels_dir/*"
        - "python -m OpenSSL.debug"
      install:
        - "pip install -r requirements.txt"
      script:
        - cd hulusubs_dl
        - python __main__.py --version
        - cd ..
      notifications:
        email:
          - xonshiz@gmail.com
    - language: python
      python:
        - 2.7
      dist: trusty
      install:
        - "pip install -r requirements.txt"
      script:
        - cd hulusubs_dl
        - python __main__.py --version
        - cd ..
      notifications:
        email:
          - xonshiz@gmail.com
    - language: python
      python:
        - 3.5
      dist: trusty
      install:
        - "pip install -r requirements.txt"
      script:
        - cd hulusubs_dl
        - python __main__.py --version
        - cd ..
      notifications:
        email:
          - xonshiz@gmail.com
    - language: python
      python: 3.8
      dist: xenial
      install:
        - "pip install -r requirements.txt"
        - "pip install pyinstaller"
      script:
        - cd hulusubs_dl
        - python __main__.py --version
        - pyinstaller --onefile --hidden-import=queue "__main__.py" -n "hulusubs_dl_linux"
        - ls
        - ls "dist"
        - cd ..
      notifications:
        email:
          - xonshiz@gmail.com
      deploy:
        - provider: pypi
          edge:
            branch: v1.8.45
          username: xonshiz
          password:
            secure: lHfaeruvQM4QL3hk1+wSwVSNjkeQH153X9Oi+nY1SaahjEg1l9mNaubfq7l8mNRgbZzW3yOHswDOLz6bNlSKX9xnjecl/5jVOg97ImChujtwZobGmCJuSBq+F2HGt3KnJefjgv2E/kAMgKPLJJSZHIGzxaYDLyRiz8hr6aMdPFEU8rY8Ha4OpHOCjQrZOULgUYQs/UR2FzjI6QhIqHOlc+reZbtADI9Z69i16iTXf+isAFgwEW+Na/uxODT3kXgt5HXxNayODPlMCVBABfWyDajoeJFmYE90hggPI3FmBn9rapTEIJMMDhT5Sh/T7lIVgyJGBA6eT4lBiEPgB4CS8Vbh6nW00RjrgYWMDPMpxqNA3hBCRsQ1zpOQc5idH8yxS2Y+7GxwWqcqmGiuvE0/a0ytU5vDeM+VkjSN1irFEW1tAPjMNHLK8aPDDteu0qCyhDK17W4NOuZ8DQgxjvPwsSIElQOTnEy4UdXNkcQa8rnPIHnHa0ceoOZI1gYdn/xlrKcmXmGSGCi4KBpo1bQ1fC6QnHleKsognpNAr4diJxgqDjRMUmcfQOWW8c2hji2xUH34amvVMZVpbJu1zkM/o8I7upaAjwE6H/s7Azo2X/sKYyH0uJDeWYrTHofp9M3yWJKJQ3/nqzG8Ete9caZBbKcj0pb6RXdJ8iAR4JLUDJE=
          distributions: "sdist bdist_wheel"
          on:
            branch: master
        - provider: releases
          api_key: $GITHUB_TOKEN
          name: "Hulusubs_dl"
          file: "hulusubs_dl/dist/hulusubs_dl_linux"
          skip_cleanup: true
          draft: true
          on:
            tags: true
            branch: master
    - os: windows
      language: sh
      python: "3.8"
      before_install:
        - choco install python --version 3.8.0
        - python --version
        - export PATH="/c/Python38:/c/Python38/Scripts:$PATH"
        - python -m pip install --upgrade pip
      env: PATH=/c/Python38:/c/Python38/Scripts:$PATH
      install:
        - "pip install -r requirements.txt"
        - "pip install pyinstaller"
      script:
        - cd hulusubs_dl
        - python __main__.py --version
        - pyinstaller --onefile --hidden-import=queue "__main__.py" -n "hulusubs_dl.exe"
        - cd dist
        - dir -s
        - dir -s
        - cd ..
        - cd ..
      notifications:
        email:
          - xonshiz@gmail.com
      deploy:
        - provider: releases
          api_key: $GITHUB_TOKEN
          name: "Hulusubs_dl"
          file: "hulusubs_dl/dist/hulusubs_dl.exe"
          skip_cleanup: true
          draft: true
          on:
            tags: true
            branch: master
    - os: osx
      language: sh
      python: "3.8"
      before_install:
        - python3 --version
        - python3 -m pip install --upgrade pip
      install:
        - "pip3 install -r requirements.txt"
        - "pip3 install pyinstaller"
      script:
        - cd hulusubs_dl
        - python3 __main__.py --version
        - pyinstaller --onefile --hidden-import=queue "__main__.py" -n "hulusubs_dl_osx"
        - ls
        - ls "dist"
        - cd ..
      notifications:
        email:
          - xonshiz@gmail.com
      deploy:
        - provider: releases
          api_key: $GITHUB_TOKEN
          name: "Hulusubs_dl"
          file: "hulusubs_dl/dist/hulusubs_dl_osx"
          skip_cleanup: true
          draft: true
          on:
            tags: true
            branch: master
