language: python
python:
  - "2.6"
  - "2.7"
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.6"
  - "pypy"
  - "pypy3"
dist: trusty
jobs:
  include:
    - python: 3.7
      dist: xenial
# command to install dependencies
install: "pip install -r requirements.txt"
# command to run tests
script:
- cd hulu_subs_dl
- python __main__.py --version
notifications:
  email:
    - xonshiz@psychoticelites.com